import type {
  Document,
  GraphEdge,
  OnboardingPlan,
  Person,
  SystemNode,
} from "./types";

export const COMPANY = {
  name: "Northline Energy",
  tagline: "Investor-owned utility · 2.1M electric customers",
  disclaimer: "Synthetic demo data. No live employee, HRIS, or message content.",
};

export const people: Person[] = [
  {
    id: "bb",
    name: "Brendan Brown",
    initials: "BB",
    title: "Principal Program Manager",
    team: "Digital / Utility Systems",
    org: "Digital",
    location: "Richmond, VA",
    startDate: "2022-04-11",
    color: "teal",
    bio: "Owns cross-system digital programs spanning customer portal, outage experience, and AMI context.",
    expertise: [
      "utility digital transformation",
      "outage experience programs",
      "OMS/GIS coordination",
      "customer portal delivery",
    ],
    priorCareer: {
      employer: "Nautilus",
      role: "Lead, Connected Device Platform",
      years: "2016–2022",
      expertise: ["connected devices", "BLE/mobile", "device telemetry", "C2M/AMI context"],
    },
    isPersona: true,
    personaLabel: "Program manager",
    managerId: "do",
  },
  {
    id: "mc",
    name: "Maya Chen",
    initials: "MC",
    title: "Customer Digital Analyst",
    team: "Customer Web",
    org: "Digital",
    location: "Richmond, VA",
    startDate: "2026-08-10",
    color: "blue",
    bio: "Week-two hire supporting the customer portal and outage-map backlog.",
    expertise: ["customer research", "digital analytics"],
    isPersona: true,
    personaLabel: "New hire",
    managerId: "np",
  },
  {
    id: "dw",
    name: "Devon Walsh",
    initials: "DW",
    title: "Solutions Architect",
    team: "Integration",
    org: "Integration",
    location: "Charlotte, NC",
    startDate: "2019-02-04",
    color: "navy",
    bio: "Designs integration patterns across OMS, C2M, and customer-facing APIs.",
    expertise: [
      "integration architecture",
      "OMS APIs",
      "notification broker",
      "event-driven design",
    ],
    isPersona: true,
    personaLabel: "Architect",
    managerId: "ps",
  },
  {
    id: "ev",
    name: "Elena Vasquez",
    initials: "EV",
    title: "Manager, Customer Operations",
    team: "Customer Operations",
    org: "Customer Ops",
    location: "Richmond, VA",
    startDate: "2014-06-01",
    color: "amber",
    bio: "Runs storm-mode customer operations and the communications review board.",
    expertise: [
      "customer operations",
      "storm response",
      "comms review",
      "regulatory customer notices",
    ],
    isPersona: true,
    personaLabel: "Manager",
  },
  {
    id: "jp",
    name: "Jordan Park",
    initials: "JP",
    title: "Cloud Platform Engineer",
    team: "Cloud Platform",
    org: "Cloud Platform",
    location: "Pittsburgh, PA",
    startDate: "2026-07-20",
    color: "sap",
    bio: "Internal transfer from Field Operations into Cloud Platform. Previously a field systems technician.",
    expertise: ["cloud platform services", "field operations context", "OT/IT boundary"],
    priorCareer: {
      employer: "Northline Field Operations",
      role: "Field Systems Technician",
      years: "2018–2026",
      expertise: ["OMS field tools", "AMI meters", "restoration workflow"],
    },
    isPersona: true,
    personaLabel: "Internal transfer",
    managerId: "gk",
  },
  {
    id: "sj",
    name: "Sarah Jones",
    initials: "SJ",
    title: "Privacy Counsel, Telemetry SME",
    team: "Privacy",
    org: "Privacy",
    location: "Richmond, VA",
    startDate: "2017-09-18",
    color: "blue",
    bio: "Internal SME for telemetry retention, AMI privacy, and customer-notice data minimization.",
    expertise: [
      "telemetry privacy",
      "data retention",
      "AMI privacy review",
      "customer notice minimization",
    ],
  },
  {
    id: "rj",
    name: "Robert Jacobson",
    initials: "RJ",
    title: "Principal Engineer, AMI Telemetry",
    team: "Integration",
    org: "Integration",
    location: "Raleigh, NC",
    startDate: "2023-01-09",
    color: "amber",
    bio: "Leads AMI head-end telemetry pipelines. Previously with Brendan at Nautilus; listed as a hiring reference.",
    expertise: ["AMI telemetry", "head-end integration", "device event streams"],
    priorCareer: {
      employer: "Nautilus",
      role: "Staff Engineer, Device Cloud",
      years: "2015–2022",
      expertise: ["connected devices", "BLE gateways", "telemetry platforms"],
    },
    managerId: "ps",
  },
  {
    id: "ps",
    name: "Priya Shah",
    initials: "PS",
    title: "OMS Integration Owner",
    team: "Integration",
    org: "Integration",
    location: "Charlotte, NC",
    startDate: "2016-03-14",
    color: "navy",
    bio: "System owner for OMS interfaces consumed by digital and operations products.",
    expertise: ["OMS integration", "outage state APIs", "runbooks"],
  },
  {
    id: "np",
    name: "Nina Patel",
    initials: "NP",
    title: "Digital PM, Customer Web",
    team: "Customer Web",
    org: "Digital",
    location: "Richmond, VA",
    startDate: "2020-08-03",
    color: "teal",
    bio: "Owns the authenticated customer portal experience, including the outage map.",
    expertise: ["customer portal", "outage map UX", "authenticated flows"],
    managerId: "do",
  },
  {
    id: "do",
    name: "Diane Okada",
    initials: "DO",
    title: "VP, Digital Experience",
    team: "Digital",
    org: "Digital",
    location: "Richmond, VA",
    startDate: "2012-01-16",
    color: "navy",
    bio: "Leads Digital. Authoritative owner of the customer experience portfolio.",
    expertise: ["digital portfolio", "experience strategy"],
  },
  {
    id: "mw",
    name: "Marcus Webb",
    initials: "MW",
    title: "Customer Operations Lead",
    team: "Customer Operations",
    org: "Customer Ops",
    location: "Richmond, VA",
    startDate: "2011-05-02",
    color: "amber",
    bio: "Storm desk lead and business owner for customer notification outcomes.",
    expertise: ["customer ops", "notification outcomes", "storm desk"],
    managerId: "ev",
  },
  {
    id: "ar",
    name: "Aisha Rahman",
    initials: "AR",
    title: "Customer Communications Lead",
    team: "Customer Communications",
    org: "Customer Ops",
    location: "Richmond, VA",
    startDate: "2018-11-12",
    color: "teal",
    bio: "Runs the customer communications review board and notice templates.",
    expertise: ["customer communications", "regulatory notices", "message templates"],
    managerId: "ev",
  },
  {
    id: "co",
    name: "Chris Okonkwo",
    initials: "CO",
    title: "GIS Data Steward",
    team: "Geospatial",
    org: "Integration",
    location: "Charlotte, NC",
    startDate: "2015-07-20",
    color: "blue",
    bio: "Stewards service-territory and outage location data used by digital products.",
    expertise: ["GIS", "service territory", "location context"],
    managerId: "ps",
  },
  {
    id: "hl",
    name: "Hannah Lee",
    initials: "HL",
    title: "IAM Architect",
    team: "Identity",
    org: "Integration",
    location: "Charlotte, NC",
    startDate: "2019-10-07",
    color: "navy",
    bio: "Owns customer identity, account association, and authenticated session design.",
    expertise: ["IAM", "account association", "customer identity"],
    managerId: "ps",
  },
  {
    id: "tb",
    name: "Tom Brennan",
    initials: "TB",
    title: "C2M Architect",
    team: "Metering Platforms",
    org: "Integration",
    location: "Raleigh, NC",
    startDate: "2013-04-22",
    color: "teal",
    bio: "Architect for Customer-to-Meter and AMI head-end integration.",
    expertise: ["C2M", "AMI", "meter-to-cash", "head-end"],
    managerId: "ps",
  },
  {
    id: "lo",
    name: "Luis Ortega",
    initials: "LO",
    title: "Notification Broker Owner",
    team: "Integration",
    org: "Integration",
    location: "Charlotte, NC",
    startDate: "2021-02-15",
    color: "amber",
    bio: "Owns the notification broker and vendor SMS/email/push connectors.",
    expertise: ["notification broker", "vendor APIs", "retry policy"],
    managerId: "ps",
  },
  {
    id: "gk",
    name: "Grace Kim",
    initials: "GK",
    title: "Data Platform Lead",
    team: "Cloud Platform",
    org: "Cloud Platform",
    location: "Pittsburgh, PA",
    startDate: "2018-06-11",
    color: "blue",
    bio: "Leads warehouse and event pipelines that land outage and notification facts.",
    expertise: ["data warehouse", "event pipelines", "cloud platform"],
  },
  {
    id: "fd",
    name: "Frank Delgado",
    initials: "FD",
    title: "OMS Operations SME",
    team: "Field Operations",
    org: "Field Operations",
    location: "Roanoke, VA",
    startDate: "1994-03-01",
    color: "navy",
    bio: "Thirty-two-year OMS operations SME. Retirement planned in six months. Holds undocumented storm-mode knowledge.",
    expertise: ["OMS operations", "storm mode", "restoration sequencing", "tribal process knowledge"],
  },
];

export const systems: SystemNode[] = [
  {
    id: "portal",
    name: "Customer Portal",
    summary: "Authenticated customer experience, including the outage map.",
    owners: ["np", "bb"],
    teams: ["Digital"],
  },
  {
    id: "oms",
    name: "OMS",
    summary: "Outage state, crew dispatch, and restoration estimates.",
    owners: ["ps", "fd"],
    teams: ["Integration", "Field Operations"],
  },
  {
    id: "gis",
    name: "GIS",
    summary: "Location, network connectivity, and service territory.",
    owners: ["co"],
    teams: ["Integration"],
  },
  {
    id: "iam",
    name: "IAM",
    summary: "Login, account association, and customer permissions.",
    owners: ["hl"],
    teams: ["Integration"],
  },
  {
    id: "c2m",
    name: "C2M",
    summary: "Customer-to-meter platform bridging CIS, AMI, and outage context.",
    owners: ["tb"],
    teams: ["Integration"],
  },
  {
    id: "ami",
    name: "AMI Head-End",
    summary: "Meter telemetry, last-gasp events, and connected-device reads.",
    owners: ["rj", "tb"],
    teams: ["Integration"],
  },
  {
    id: "notify",
    name: "Notification Broker",
    summary: "Routes SMS, email, push, and IVR through vendor APIs.",
    owners: ["lo"],
    teams: ["Integration", "Customer Ops"],
    vendors: ["RelayNotice", "ClearPage IVR"],
  },
  {
    id: "comms",
    name: "Customer Communications",
    summary: "Notice templates, regulatory language, and review board.",
    owners: ["ar", "ev"],
    teams: ["Customer Ops"],
  },
  {
    id: "dwh",
    name: "Data Warehouse",
    summary: "Analytical copy of outage, notification, and meter events.",
    owners: ["gk"],
    teams: ["Cloud Platform"],
  },
  {
    id: "mobile",
    name: "Mobile App",
    summary: "Customer mobile experience; consumes portal and notification APIs.",
    owners: ["np"],
    teams: ["Digital"],
  },
  {
    id: "cis",
    name: "CIS",
    summary: "Customer information system of record for accounts and premises.",
    owners: ["mw"],
    teams: ["Customer Ops"],
  },
];

export const documents: Document[] = [
  {
    id: "app-registry",
    title: "Application Registry",
    kind: "CMDB / APM",
    trustType: "authoritative",
    updated: "2026-03-12",
    owner: "Enterprise Architecture",
    excerpt:
      "Customer Digital owns the Customer Portal and outage-map experience. OMS remains the system of record for outage state. GIS is the system of record for location.",
    systems: ["portal", "oms", "gis", "iam"],
    people: ["np", "ps", "co", "hl"],
  },
  {
    id: "adr-014",
    title: "Outage Digital ADR-014",
    kind: "Architecture decision",
    trustType: "source-grounded",
    updated: "2025-11-04",
    owner: "Nina Patel",
    excerpt:
      "Outage-map changes must be reviewed with OMS integration, GIS data stewardship, IAM, and Customer Communications because the map composes four systems of record.",
    systems: ["portal", "oms", "gis", "iam", "comms"],
    people: ["np", "bb", "ps", "co", "hl", "ar"],
  },
  {
    id: "comms-sop",
    title: "Customer Communications SOP",
    kind: "SOP",
    trustType: "authoritative",
    updated: "2025-08-19",
    owner: "Aisha Rahman",
    excerpt:
      "Any customer-visible outage copy, estimated restoration time, or map legend change requires Customer Communications review before production.",
    systems: ["portal", "comms", "notify"],
    people: ["ar", "ev", "mw"],
  },
  {
    id: "oms-runbook",
    title: "OMS Integration Runbook",
    kind: "Runbook",
    trustType: "source-grounded",
    updated: "2026-01-22",
    owner: "Priya Shah",
    excerpt:
      "Portal and mobile consume OMS outage polygons and ETR via the integration layer. Schema changes require Priya Shah and a digital PM.",
    systems: ["oms", "portal", "mobile"],
    people: ["ps", "bb", "dw"],
  },
  {
    id: "outage-diagram-2023",
    title: "Outage-Map Ownership Diagram (2023)",
    kind: "Diagram",
    trustType: "source-grounded",
    updated: "2023-04-11",
    owner: "Legacy PMO",
    excerpt:
      "Lists Team A as outage-map owner. Superseded by the Application Registry, which names Customer Digital.",
    stale: true,
    conflictsWith: "app-registry",
    systems: ["portal"],
    people: [],
  },
  {
    id: "adr-022",
    title: "Telemetry Data-Retention ADR-022",
    kind: "Architecture decision",
    trustType: "source-grounded",
    updated: "2025-06-18",
    owner: "Sarah Jones",
    excerpt:
      "AMI and connected-device telemetry retained 24 months operational, 7 years billing-grade. Privacy review required before new device classes.",
    systems: ["ami", "c2m", "dwh"],
    people: ["sj", "rj", "tb"],
  },
  {
    id: "inc-2417",
    title: "INC-2417 Post-Incident Review",
    kind: "Incident",
    trustType: "source-grounded",
    updated: "2024-09-07",
    owner: "Luis Ortega",
    excerpt:
      "Prior notification vendor change failed UAT: duplicate SMS retries during storm mode. Root cause was dual retry policies in broker and vendor.",
    systems: ["notify", "portal", "mobile", "oms"],
    people: ["lo", "mw", "ar", "dw"],
  },
  {
    id: "vendor-notify",
    title: "Notification Vendor Contract Summary",
    kind: "Contract",
    trustType: "authoritative",
    updated: "2025-02-03",
    owner: "Vendor Management",
    excerpt:
      "RelayNotice (SMS/push) and ClearPage IVR. API version freeze through 2026-Q4. Replacement requires legal, privacy, and integration sign-off.",
    systems: ["notify"],
    people: ["lo", "sj"],
  },
  {
    id: "pr-441",
    title: "Privacy Review Checklist PR-441",
    kind: "Policy",
    trustType: "authoritative",
    updated: "2026-01-09",
    owner: "Sarah Jones",
    excerpt:
      "Customer notification content, phone numbers, and outage premise linkage are in-scope for privacy review on vendor or API changes.",
    systems: ["notify", "cis", "portal"],
    people: ["sj", "ar"],
  },
  {
    id: "gis-standard",
    title: "GIS Service Territory Data Standard",
    kind: "Standard",
    trustType: "authoritative",
    updated: "2025-10-02",
    owner: "Chris Okonkwo",
    excerpt:
      "Outage polygons must use the current GIS connectivity model. Digital teams do not author network geometry.",
    systems: ["gis", "portal", "oms"],
    people: ["co"],
  },
  {
    id: "iam-spec",
    title: "IAM Account Association Spec",
    kind: "Specification",
    trustType: "source-grounded",
    updated: "2025-12-14",
    owner: "Hannah Lee",
    excerpt:
      "Authenticated outage views require premise-to-login association. Guest map is unauthenticated and must not leak account data.",
    systems: ["iam", "portal"],
    people: ["hl", "np"],
  },
  {
    id: "glossary",
    title: "Northline Acronym Glossary",
    kind: "Reference",
    trustType: "source-grounded",
    updated: "2026-02-01",
    owner: "Digital PMO",
    excerpt:
      "OMS: Outage Management System. GIS: Geographic Information System. C2M: Customer-to-Meter. AMI: Advanced Metering Infrastructure. IAM: Identity and Access Management.",
    systems: [],
    people: [],
  },
  {
    id: "change-gate",
    title: "Digital Change Gate Policy",
    kind: "Policy",
    trustType: "authoritative",
    updated: "2025-09-30",
    owner: "Diane Okada",
    excerpt:
      "Cross-system customer experience changes require an impact review listing systems, teams, vendors, and privacy before architecture review.",
    systems: ["portal", "notify", "oms"],
    people: ["do", "bb"],
  },
  {
    id: "c2m-overview",
    title: "C2M Platform Overview",
    kind: "Overview",
    trustType: "source-grounded",
    updated: "2025-07-21",
    owner: "Tom Brennan",
    excerpt:
      "C2M associates meters, premises, and customers. Digital outage and usage experiences depend on C2M, not on CIS directly.",
    systems: ["c2m", "ami", "cis", "portal"],
    people: ["tb", "rj"],
  },
];

export const edges: GraphEdge[] = [
  { id: "e1", from: "do", to: "bb", kind: "manages", label: "Manager" },
  { id: "e2", from: "do", to: "np", kind: "manages", label: "Manager" },
  { id: "e3", from: "np", to: "mc", kind: "manages", label: "Manager" },
  { id: "e4", from: "ps", to: "dw", kind: "manages", label: "Manager" },
  { id: "e5", from: "ps", to: "rj", kind: "manages", label: "Manager" },
  { id: "e6", from: "ps", to: "lo", kind: "manages", label: "Manager" },
  { id: "e7", from: "ev", to: "mw", kind: "manages", label: "Manager" },
  { id: "e8", from: "ev", to: "ar", kind: "manages", label: "Manager" },
  { id: "e9", from: "gk", to: "jp", kind: "manages", label: "Manager" },
  { id: "e10", from: "bb", to: "np", kind: "collaborated", label: "Shared outage-map program" },
  { id: "e11", from: "bb", to: "ps", kind: "collaborated", label: "OMS digital integration" },
  { id: "e12", from: "sj", to: "rj", kind: "contributed", label: "Co-authored ADR-022" },
  { id: "e13", from: "sj", to: "tb", kind: "collaborated", label: "AMI privacy reviews" },
  { id: "e14", from: "rj", to: "bb", kind: "prior-employer", label: "Worked together at Nautilus", optIn: "career" },
  { id: "e15", from: "rj", to: "bb", kind: "reference", label: "Robert listed Brendan as a reference", optIn: "reference" },
  { id: "e16", from: "lo", to: "mw", kind: "collaborated", label: "Storm-mode notification outcomes" },
  { id: "e17", from: "lo", to: "ar", kind: "collaborated", label: "Notice template integration" },
  { id: "e18", from: "fd", to: "ps", kind: "collaborated", label: "OMS operations ↔ integration" },
  { id: "e19", from: "jp", to: "fd", kind: "collaborated", label: "Field tools while in operations" },
  { id: "e20", from: "portal", to: "oms", kind: "depends-on", label: "Outage state" },
  { id: "e21", from: "portal", to: "gis", kind: "depends-on", label: "Location context" },
  { id: "e22", from: "portal", to: "iam", kind: "depends-on", label: "Authenticated flow" },
  { id: "e23", from: "portal", to: "notify", kind: "depends-on", label: "Customer alerts" },
  { id: "e24", from: "notify", to: "cis", kind: "depends-on", label: "Contact records" },
  { id: "e25", from: "notify", to: "oms", kind: "depends-on", label: "Outage events" },
  { id: "e26", from: "c2m", to: "ami", kind: "depends-on", label: "Meter telemetry" },
  { id: "e27", from: "c2m", to: "cis", kind: "depends-on", label: "Account/premise" },
  { id: "e28", from: "oms", to: "gis", kind: "depends-on", label: "Network model" },
  { id: "e29", from: "oms", to: "c2m", kind: "depends-on", label: "Meter last-gasp" },
  { id: "e30", from: "mobile", to: "portal", kind: "depends-on", label: "Experience APIs" },
  { id: "e31", from: "mobile", to: "notify", kind: "depends-on", label: "Push" },
  { id: "e32", from: "dwh", to: "notify", kind: "depends-on", label: "Notification facts" },
  { id: "e33", from: "dwh", to: "oms", kind: "depends-on", label: "Outage facts" },
  { id: "e34", from: "np", to: "portal", kind: "owns", label: "Experience owner" },
  { id: "e35", from: "ps", to: "oms", kind: "owns", label: "Integration owner" },
  { id: "e36", from: "lo", to: "notify", kind: "owns", label: "Broker owner" },
];

export const ACRONYMS = [
  { term: "OMS", meaning: "Outage Management System — source of outage state and restoration estimates." },
  { term: "GIS", meaning: "Geographic Information System — network model and service territory." },
  { term: "IAM", meaning: "Identity and Access Management — login and account association." },
  { term: "C2M", meaning: "Customer-to-Meter — associates customers, premises, and meters." },
  { term: "AMI", meaning: "Advanced Metering Infrastructure — meters and head-end telemetry." },
  { term: "CIS", meaning: "Customer Information System — accounts, billing, contact records." },
  { term: "ADR", meaning: "Architecture Decision Record — why a system is the way it is." },
  { term: "ETR", meaning: "Estimated Time of Restoration — shown on the outage map and in notices." },
];

export const onboardingByPersona: Record<string, OnboardingPlan> = {
  bb: {
    title: "Role navigation plan",
    subtitle: "You already know Digital. This plan maps the systems and people your current programs depend on.",
    phases: [
      { when: "This week", what: "Confirm OMS/GIS/IAM owners for the outage-map increment", progress: 100 },
      { when: "This month", what: "Walk notification broker retry policy with Luis before vendor talks", progress: 62 },
      { when: "Quarter", what: "Lead a cross-functional impact review with an All-Aboard briefing", progress: 28 },
      { when: "H2", what: "Capture Frank Delgado’s storm-mode OMS knowledge before retirement", progress: 8 },
    ],
    peopleToMeet: [
      { personId: "ps", why: "OMS integration owner for every outage-map change" },
      { personId: "lo", why: "Notification broker and vendor API risk" },
      { personId: "sj", why: "Privacy gate on telemetry and notices" },
      { personId: "fd", why: "Undocumented OMS storm-mode knowledge" },
    ],
    acronyms: ACRONYMS,
    note: "Meetings are recommended from assigned work and system dependencies — not popularity.",
  },
  mc: {
    title: "Adaptive 30 / 60 / 90",
    subtitle: "Week-two plan for a Customer Digital Analyst on the portal and outage-map backlog.",
    phases: [
      { when: "Week 1", what: "Org map, acronym glossary, system overview, data access basics", progress: 100 },
      { when: "Weeks 2–4", what: "Customer digital systems, owners, recurring forums, historical decisions", progress: 22 },
      { when: "Month 2", what: "Dependency map, vendor context, current portfolio, change gates", progress: 0 },
      { when: "Month 3", what: "Support a cross-functional impact review with AI briefing support", progress: 0 },
    ],
    peopleToMeet: [
      { personId: "np", why: "Your manager and portal experience owner" },
      { personId: "bb", why: "Program context for outage-map coordination" },
      { personId: "ps", why: "OMS integration — the system behind the map" },
      { personId: "ar", why: "Customer communications review board" },
    ],
    acronyms: ACRONYMS,
    note: "All-Aboard recommends meetings from assigned work, system dependencies, and permissioned org context — not popularity scoring.",
  },
  dw: {
    title: "Architect context pack",
    subtitle: "Systems, owners, and historical decisions for integration architecture work.",
    phases: [
      { when: "Now", what: "Notification broker dual-retry history (INC-2417) before any vendor API change", progress: 80 },
      { when: "This sprint", what: "Confirm C2M ↔ OMS last-gasp contract with Tom and Priya", progress: 45 },
      { when: "This quarter", what: "Map privacy review PR-441 against broker payloads", progress: 20 },
      { when: "Next", what: "Document Frank’s storm-mode OMS sequencing as a governed runbook", progress: 5 },
    ],
    peopleToMeet: [
      { personId: "lo", why: "Broker owner and INC-2417 author" },
      { personId: "tb", why: "C2M / AMI contract" },
      { personId: "sj", why: "Privacy constraints on telemetry payloads" },
      { personId: "fd", why: "Operational reality of OMS during storms" },
    ],
    acronyms: ACRONYMS,
    note: "This is a systems-first plan. People appear because they own a dependency, not because they are well-networked.",
  },
  ev: {
    title: "Operations context pack",
    subtitle: "Who actually knows the systems your team is asked to bless — without ranking employees.",
    phases: [
      { when: "This week", what: "Review communications SOP against the current outage-map increment", progress: 70 },
      { when: "This month", what: "Confirm privacy + vendor implications of any notice-channel change", progress: 35 },
      { when: "Storm season", what: "Rehearse broker retry behavior with Integration using INC-2417", progress: 15 },
      { when: "Succession", what: "Sponsor capture of Frank Delgado’s OMS storm-mode knowledge", progress: 10 },
    ],
    peopleToMeet: [
      { personId: "ar", why: "Communications review board lead" },
      { personId: "mw", why: "Storm desk and notification outcomes" },
      { personId: "lo", why: "Broker behavior during storms" },
      { personId: "bb", why: "Digital program coordination" },
    ],
    acronyms: ACRONYMS,
    note: "Managers see expertise in context of work. All-Aboard will not produce collaboration scores or networking ranks.",
  },
  jp: {
    title: "Re-onboarding plan",
    subtitle: "You moved from Field Operations to Cloud Platform. This skips utility basics you already know.",
    phases: [
      { when: "Week 1", what: "Cloud platform services, data warehouse landing zones, access model", progress: 55 },
      { when: "Weeks 2–4", what: "How OMS/AMI events become warehouse facts; owners and SLAs", progress: 18 },
      { when: "Month 2", what: "Current portfolio, change gates, and the notification pipeline", progress: 0 },
      { when: "Month 3", what: "Lead a small impact review on a warehouse consumer change", progress: 0 },
    ],
    peopleToMeet: [
      { personId: "gk", why: "Your new manager and warehouse owner" },
      { personId: "tb", why: "C2M is the bridge from meters you already know" },
      { personId: "ps", why: "OMS integration — your field context is an asset here" },
      { personId: "dw", why: "Event-driven patterns used by Cloud Platform" },
    ],
    acronyms: ACRONYMS,
    note: "Re-onboarding uses your Field Operations history as an asset, not a gap. Prior-role expertise is included because it is employer-authoritative.",
  },
};

export const personas = people.filter((p) => p.isPersona);
export const personById = Object.fromEntries(people.map((p) => [p.id, p]));
export const systemById = Object.fromEntries(systems.map((s) => [s.id, s]));
export const documentById = Object.fromEntries(documents.map((d) => [d.id, d]));
